# Generated by Django 5.0.13 on 2025-04-14 15:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Large_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên khu')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Khu lớn',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Small_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên khu')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Large_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_small_area', to='sleekweb.large_area')),
            ],
            options={
                'verbose_name_plural': 'Khu nhỏ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='XY_cn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên khu')),
                ('Phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số đt')),
                ('Working_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thời gian làm việc')),
                ('Overnight', models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='Thời gian làm việc')),
                ('Year_of_birth', models.CharField(blank=True, max_length=50, null=True, verbose_name='Năm sinh')),
                ('Height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chiều cao')),
                ('Weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cân nặng')),
                ('Rounds', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số đo 3 vòng')),
                ('Service', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Dịch vụ')),
                ('Segment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phân khúc')),
                ('Content', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Large_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_XY_large_cn', to='sleekweb.large_area')),
                ('Belong_Small_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_XY_small_cn', to='sleekweb.small_area')),
            ],
            options={
                'verbose_name_plural': 'Người tham gia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='XY_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên khu')),
                ('Phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số đt')),
                ('Working_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thời gian làm việc')),
                ('Overnight', models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='Thời gian làm việc')),
                ('Year_of_birth', models.CharField(blank=True, max_length=50, null=True, verbose_name='Năm sinh')),
                ('Height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chiều cao')),
                ('Weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cân nặng')),
                ('Rounds', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số đo 3 vòng')),
                ('Service', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Dịch vụ')),
                ('Segment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phân khúc')),
                ('Content', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Large_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_XY_large_en', to='sleekweb.large_area')),
                ('Belong_Small_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_XY_small_en', to='sleekweb.small_area')),
            ],
            options={
                'verbose_name_plural': 'Người tham gia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Avatar', models.ImageField(blank=True, default='user_image/user_empty.png', null=True, upload_to='user_image')),
                ('Full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('Phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số điện thoại')),
                ('OTP', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã Otp')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='sleekweb_us_usernam_8b077a_idx'), models.Index(fields=['email'], name='sleekweb_us_email_49565d_idx'), models.Index(fields=['Full_name'], name='sleekweb_us_Full_na_55d14c_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
