# Generated by Django 5.0.13 on 2025-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='xy_cn',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='uuid'),
        ),
        migrations.AddField(
            model_name='xy_en',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='xy_cn',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên NV'),
        ),
        migrations.AlterField(
            model_name='xy_en',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên NV'),
        ),
        migrations.AlterField(
            model_name='xy_en',
            name='Overnight',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='Qua đêm'),
        ),
    ]
