# Generated by Django 5.0.13 on 2025-04-21 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0003_xy_cn_uuid_xy_en_uuid_alter_xy_cn_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(blank=True, null=True, upload_to='VIDEOS')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_XY_cn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_video_cn', to='sleekweb.xy_cn')),
                ('Belong_XY_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_video_en', to='sleekweb.xy_en')),
            ],
            options={
                'verbose_name_plural': 'Video nhân viên',
                'ordering': ['id'],
            },
        ),
    ]
