# Generated by Django 5.0.13 on 2025-04-22 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('End_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Phê duyệt')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Thời hạn',
                'ordering': ['id'],
            },
        ),
    ]
