# Generated by Django 5.0.13 on 2025-04-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0005_time_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_user',
            name='Active',
        ),
    ]
