# Generated by Django 5.0.13 on 2025-04-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0006_remove_time_user_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XY_en',
            new_name='XY',
        ),
        migrations.RemoveField(
            model_name='video',
            name='Belong_XY_cn',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='Belong_XY_cn',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='Belong_XY_en',
        ),
        migrations.RemoveField(
            model_name='video',
            name='Belong_XY_en',
        ),
        migrations.DeleteModel(
            name='XY_cn',
        ),
    ]
