# Generated by Django 5.0.13 on 2025-04-22 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0007_rename_xy_en_xy_remove_video_belong_xy_cn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Belong_XY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_photo_en', to='sleekweb.xy'),
        ),
        migrations.AddField(
            model_name='video',
            name='Belong_XY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_video_en', to='sleekweb.xy'),
        ),
        migrations.AddField(
            model_name='xy',
            name='Belong_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_xy', to=settings.AUTH_USER_MODEL),
        ),
    ]
