# Generated by Django 5.0.13 on 2025-04-22 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0008_photo_belong_xy_video_belong_xy_xy_belong_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên quốc gia')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Khu nhỏ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Châu lục')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Khu lớn',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='xy',
            name='Belong_Large_area',
        ),
        migrations.RemoveField(
            model_name='small_area',
            name='Belong_Large_area',
        ),
        migrations.RemoveField(
            model_name='xy',
            name='Belong_Small_area',
        ),
        migrations.AlterField(
            model_name='photo',
            name='Belong_XY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_photo', to='sleekweb.xy'),
        ),
        migrations.AlterField(
            model_name='video',
            name='Belong_XY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_video', to='sleekweb.xy'),
        ),
        migrations.AddField(
            model_name='xy',
            name='Belong_Nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_XY_nation', to='sleekweb.nation'),
        ),
        migrations.AddField(
            model_name='nation',
            name='Belong_Region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_nation', to='sleekweb.region'),
        ),
        migrations.AddField(
            model_name='xy',
            name='Belong_Region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_XY_region', to='sleekweb.region'),
        ),
        migrations.DeleteModel(
            name='Large_area',
        ),
        migrations.DeleteModel(
            name='Small_area',
        ),
    ]
