# Generated by Django 5.0.13 on 2025-04-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0009_nation_region_remove_xy_belong_large_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xy',
            name='Price',
            field=models.TextField(blank=True, null=True, verbose_name='Giá'),
        ),
    ]
