# Generated by Django 5.0.13 on 2025-04-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0010_xy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xy',
            name='Price',
        ),
        migrations.AddField(
            model_name='xy',
            name='Price_call_in',
            field=models.TextField(blank=True, null=True, verbose_name='Giá gọi đến'),
        ),
        migrations.AddField(
            model_name='xy',
            name='Price_call_out',
            field=models.TextField(blank=True, null=True, verbose_name='Giá gọi ra'),
        ),
    ]
