# Generated by Django 5.0.13 on 2025-04-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0011_remove_xy_price_xy_price_call_in_xy_price_call_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='xy',
            name='Count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số thứ tự'),
        ),
        migrations.AlterField(
            model_name='time_user',
            name='End_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian Kết thúc'),
        ),
    ]
