# Generated by Django 5.0.13 on 2025-04-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0013_rename_count_xy_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xy',
            name='Working_time',
        ),
    ]
