# Generated by Django 5.0.13 on 2025-05-09 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0014_remove_xy_working_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='xy',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='AVATAR_PRODUCT'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='Belong_Region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_nation', to='sleekweb.region'),
        ),
    ]
