# Generated by Django 5.0.13 on 2025-05-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0015_xy_avatar_alter_nation_belong_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xy',
            name='Service',
        ),
    ]
