# Generated by Django 5.0.13 on 2025-05-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0016_remove_xy_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='xy',
            name='Service',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
    ]
